use_frameworks!

platform :ios, '9.0'

target 'RVSubscriptionCenter_Example' do
  pod 'RVSubscriptionCenter', :path => '../'

  target 'RVSubscriptionCenter_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
